In [1]:
"""
Simple exercises to get used to TensorFlow API
You should thoroughly test your code.
TensorFlow's official documentation should be your best friend here
CS20: "TensorFlow for Deep Learning Research"
cs20.stanford.edu
Created by Chip Huyen (chiphuyen@cs.stanford.edu)
"""
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

import tensorflow as tf

sess = tf.InteractiveSession()

/home/joel/anaconda3/envs/tf/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################
x = tf.random_normal([],name='x')
y = tf.random_normal([],name='y')
ans_1 = tf.cond(tf.greater(x,y),lambda: tf.add(x,y),lambda: tf.subtract(x,y))
sess.run([x,y,ans_1])

[-2.4241366, 1.506267, -3.9304037]

In [17]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from the range [-1, 1).
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################
z = tf.random_uniform([],minval=-1,maxval=1)
w = tf.random_uniform([],minval=-1,maxval=1)
def fn1(): return tf.cond(tf.equal(z,w),lambda: tf.zeros([]),lambda: tf.subtract(z,w))
ans_2 = tf.cond(tf.less(z,w),lambda: tf.add(z,w),fn1)
out = tf.case({tf.less(z,w):lambda:tf.add(z,w),tf.greater(z, w): lambda: tf.subtract(z, w)},default=lambda: tf.constant(0.0), exclusive=True)
sess.run([z,w,ans_2,out])

[-0.61509323, 0.70092154, 0.085828304, 0.085828304]

In [18]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################
x = tf.constant([[0, -2, -1], [0, 1, 2]],dtype="float32",name="const_x")
y = tf.zeros(x.shape)
# or tf.zeros_like(x)
sess.run(tf.equal(x,y,"equal_x_y"))

array([[ True, False, False],
       [ True, False, False]])

In [20]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################
arr = [29.05088806,  27.61298943,  31.19073486,  29.35532951,
 30.97266006,  26.67541885,  38.08450317,  20.74983215,
 34.94445419,  34.45999146,  29.06485367,  36.01657104,
 27.88236427,  20.56035233,  30.20379066,  29.51215172,
 33.71149445,  28.59134293,  36.05556488,  28.66994858]
x = tf.constant(arr,dtype="float32")
indices = tf.where(x > 30)
print("{0} {1}".format(sess.run(indices),sess.run(tf.gather(x,indices=indices))))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]] [[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [6]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################
sess.run(tf.diag(tf.range(1,7)))

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]], dtype=int32)

In [21]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################
ran_mat = tf.random_normal((10,10),mean=10,stddev=1)
sess.run([ran_mat,tf.matrix_determinant(ran_mat)])

[array([[11.370145 ,  9.865634 , 10.097978 , 10.823208 , 10.069962 ,
         10.844887 ,  9.477124 , 10.356702 ,  9.899151 , 10.527064 ],
        [ 9.410095 ,  9.601612 ,  9.252334 , 10.858159 , 10.552427 ,
          9.881888 ,  9.789231 , 10.129561 ,  9.728655 ,  9.025435 ],
        [10.672534 ,  9.511955 , 10.678213 ,  9.292104 , 10.812033 ,
         10.291742 ,  9.307807 , 10.084117 ,  9.906007 ,  8.663023 ],
        [10.93027  , 10.291708 ,  8.368289 ,  9.345234 ,  7.974103 ,
         10.16992  ,  9.946216 , 10.061315 ,  8.966318 ,  8.476199 ],
        [ 9.428619 , 10.959448 , 10.250418 ,  7.6016045,  9.676426 ,
         10.939677 , 10.8481   , 10.495489 ,  9.219929 ,  9.257703 ],
        [10.614498 , 11.171098 ,  9.504447 ,  9.93621  , 10.518507 ,
          9.1671505,  9.970791 ,  9.02618  ,  9.361233 , 11.041529 ],
        [ 9.581764 , 10.244398 ,  9.702659 , 10.796526 ,  9.049619 ,
          8.795648 , 10.247463 , 12.538597 ,  8.31203  ,  9.916611 ],
        [ 9.601653 ,  8.795

In [8]:

###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
uni = sess.run(tf.unique(x))
list(uni[0])

[5, 2, 3, 10, 6, 4, 1, 0, 9]

In [22]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################
x = tf.random_normal([300],mean=5,stddev=1)
y = tf.random_normal((1,300),mean=5,stddev=1)
# print(sess.run([x,y]))
f_1 = lambda :tf.reduce_mean(tf.square(x-y))
f_2 = lambda :tf.reduce_mean(tf.abs(x-y))
sess.run(tf.cond(tf.reduce_mean(x-y)<0,f_1,f_2))

1.8437566